#!/bin/bash
#
# reportprocess	Joborder
#
# chkconfig: - 64 36
# description: Joborder background process
# processname: nohup /usr/bin/java -jar /var/www/html/jo-dev.ish.co.id/application/commands/joborder/Joborder.jar &
check_status() {
	s=`pgrep -f "Joborder"`
	if [ $s ] ; then
		echo $s
	else
		echo 0
	fi
}

start() {
	pid=$(check_status)

	if [ $pid -ne 0 ] ; then
		echo "Joborder is already started [PID: $pid]."
		exit 1
	fi

	echo -n "Starting Joborder: "
	nohup /usr/bin/java -jar /var/www/html/jo-dev.ish.co.id/application/commands/joborder/Joborder.jar > /dev/null 2>&1 &
	echo $! > "/var/www/html/jo-dev.ish.co.id/application/runtime/Joborder.pid"
	echo "[OK]"
}

stop() {
	pid=$(check_status)

	if [ $pid -eq 0 ] ; then
		echo "Joborder is already stopped."
		exit 1
	fi

	echo -n "Stopping Joborder: "
	kill -9 $pid &
	echo "[OK]"
}

status() {
	pid=$(check_status $1)

	if [ $pid -ne 0 ] ; then
		echo "Joborder is started [PID: $pid]."
	else
		echo "Joborder is stopped."
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|status}"
		exit 1
esac

exit 0
